### PR TITLE
storage: sledDb

### PR DESCRIPTION
**Pull request by 0del**
- sled architect [Checkpointing](https://github.com/spacejam/sled/wiki/sled-architectural-outlook#checkpointing)

### CODE REVIEW

**Comment by sabledb-io** [comment]
Thanks, that was on my todo list. I will soon look at it!

**Comment by 0del** [comment]
@sabledb-io so, should i close this ?

**Comment by sabledb-io** [comment]
No, I am working on other stuff...if you could get it to work it will be great.
I had an implementation 2 months ago, but I dropped it. The only gap that is missing is the `checkpoint`, the rest is straight forward. The checkpoint is needed for replication

**Comment by 0del** [comment]
Yeah, I saw the gap, I'm still working on it.

**Comment by sabledb-io** [comment]
FYI: I will be reviewing this once all tests are passing

**Comment by 0del** [comment]
still work with this https://github.com/spacejam/sled/issues/1198

**Comment by sabledb-io** [comment]
Closing this PR due to inactivity

**Pull request closed without merging**
